name: Docker Build and Push

on: [push]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: azure/docker-login@v1
      with:
        login-server: docker.pkg.github.com
        username: vverst
        password: ${{ secrets.GITHUB_TOKEN }}
    - run: |
        docker build . -t docker.pkg.github.com/vverst/bitwarden_rs/bwrs:${{ github.sha }}
        docker push docker.pkg.github.com/vverst/bitwarden_rs/bwrs:${{ github.sha }}
