name: Docker Build and Push

on: [push]

jobs:

  build:
 
    runs-on: ubuntu-latest
 
    steps:
    - uses: actions/checkout@v1
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag "{{ secrets.DOCKER_HUB_USERNAME }}/bwrs:$(date +%s)"
    - name: Login Docker Hub
      run: docker login -u {{ secrets.DOCKER_HUB_USERNAME }} -p {{ secrets.DOCKER_HUB_PASSWORD }}
    - name: Docker push
      run: docker push 
