name: Docker Build and Push

on: [push]

jobs:

  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch: [aarch64, amd64, armv6, armv7]
        db: [sqlite, mysql]
        os: [alpine, debian]
        include:
          - os: debian
            dockerfile: Dockerfile
          - os: alpine
            dockerfile: Dockerfile.alpine
        exclude:
        - arch: aarch64
          os: alpine
        - arch: armv6
          os: alpine
        - arch: armv7
          os: alpine
    steps:
    - uses: actions/checkout@v1
    - uses: azure/docker-login@v1
      with:
        login-server: docker.pkg.github.com
        username: vverst
        password: ${{ secrets.GITHUB_TOKEN }}
    - run: env
    - run: |
        echo docker.pkg.github.com/${GITHUB_REPOSITORY}/test
        docker build . -f ./docker/${{ matrix.arch }}/${{ matrix.db }}/${{ matrix.dockerfile }} -t docker.pkg.github.com/${GITHUB_REPOSITORY}/${{ matrix.arch }}/${{ matrix.db }}/${{ matrix.os }}:${{ github.sha }}
        docker push docker.pkg.github.com/${GITHUB_REPOSITORY}/${{ matrix.arch }}/${{ matrix.db }}/${{ matrix.os }}:${{ github.sha }}
