name: Docker Build and Push

on: [push]

jobs:
  one:
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: Dump job context
        env:
          JOB_CONTEXT: ${{ toJson(job) }}
        run: echo "$JOB_CONTEXT"
      - name: Dump steps context
        env:
          STEPS_CONTEXT: ${{ toJson(steps) }}
        run: echo "$STEPS_CONTEXT"
      - name: Dump runner context
        env:
          RUNNER_CONTEXT: ${{ toJson(runner) }}
        run: echo "$RUNNER_CONTEXT"
      - name: Dump strategy context
        env:
          STRATEGY_CONTEXT: ${{ toJson(strategy) }}
        run: echo "$STRATEGY_CONTEXT"
      - name: Dump matrix context
        env:
          MATRIX_CONTEXT: ${{ toJson(matrix) }}
        run: echo "$MATRIX_CONTEXT"
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        arch: [aarch64, amd64, armv6, armv7]
        db: [sqlite, mysql]
        os: [alpine, debian]
        include:
          - os: debian
            dockerfile: Dockerfile
          - os: alpine
            dockerfile: Dockerfile.alpine
        exclude:
          # Exclude non existing alpine versions
        - arch: aarch64
          os: alpine
        - arch: armv6
          os: alpine
        - arch: armv7
          os: alpine
          # Exclude following mysql builds since they are not building correctly:
        - arch: aarch64
          db: mysql
        - arch: armv6
          db: mysql
        - arch: armv7
          db: mysql

    steps:
    - uses: actions/checkout@v1
    - uses: azure/docker-login@v1
      with:
        login-server: docker.pkg.github.com
        username: ${{ github.repository.owner.login }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - run: env
    - run: |
        echo docker.pkg.github.com/${GITHUB_REPOSITORY}/test
        docker build . -f ./docker/${{ matrix.arch }}/${{ matrix.db }}/${{ matrix.dockerfile }} -t docker.pkg.github.com/${GITHUB_REPOSITORY}/${{ matrix.arch }}-${{ matrix.db }}-${{ matrix.os }}:${GITHUB_REF##*/}
        docker push docker.pkg.github.com/${GITHUB_REPOSITORY}/${{ matrix.arch }}-${{ matrix.db }}-${{ matrix.os }}:${GITHUB_REF##*/}
